version: '3.4'

services:

  aliasmanager:
    image: aliasmanager
    hostname: api
    build:
        context: AliasManager/
        dockerfile: Dockerfile
    networks:
        - customnetwork
    links:
        - db
    depends_on:
        - db

  aliasmanagermigration:
    image: alias-manager-migration
    build:
      context: AliasManager.Repository.Migration/
      dockerfile: Dockerfile
    networks:
        - customnetwork
    environment:
        DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
    links:
        - db
    depends_on:
        - db

  db:
    image: postgres
    hostname: database
    restart: always
    build:
        context: CustomPostgresql/
        dockerfile: Dockerfile
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
        - customnetwork
    environment:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:

networks:
  customnetwork:
    driver: bridge