CREATE ROLE mail_user WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'groke305yo3owkdjvneDfmw1rGrg';

CREATE DATABASE mail
    WITH 
    OWNER = postgres;